import { spawnSync } from "node:child_process";
import path from "node:path";
import {
  applyFix,
  type FixPlan,
  PARAM_RULE_CITATION,
  PROMPT_RULE_CITATION,
  planFix,
  renderUnifiedDiff,
} from "../fix/index.js";
import { bold, cyan, dim, green, red, yellow } from "../output/colors.js";
import { plural } from "../output/format.js";
import {
  COMMON_OPTIONS,
  flag,
  type IO,
  int,
  loadIndex,
  parse,
  resolveRoot,
  resolveToday,
  str,
  UsageError,
} from "./shared.js";

export const FIX_HELP = `Usage: modelshift fix [path] [options]

Rewrites retired, retiring and deprecated model IDs to the provider's recommended
replacement, removes sampling parameters the target rejects, and flags prompt text
that Anthropic's guidance says to reconsider. Dry run by default: prints a unified diff.

Options:
  --write             Apply the changes to disk
  --pr                Apply, commit on a new branch and open a pull request with gh
  --branch <name>     Branch name for --pr (default modelshift/migrate-<date>)
  --days <n>          Window used to classify "retiring" (default 90)
  --include-eligible  Also rewrite models that are only eligible for retirement (off by default)
  --no-gitignore      Do not honour .gitignore files
  --registry <file>   Use a different lifecycle.json
  --today <date>      Evaluate as of this ISO date
  --json              Print machine readable output
  -h, --help          Show this help
`;

const OPTIONS = {
  ...COMMON_OPTIONS,
  write: { type: "boolean" as const },
  pr: { type: "boolean" as const },
  branch: { type: "string" as const },
  days: { type: "string" as const },
  "include-eligible": { type: "boolean" as const },
};

function colorDiff(diff: string): string {
  return diff
    .split("\n")
    .map((line) => {
      if (line.startsWith("+++") || line.startsWith("---")) return bold(line);
      if (line.startsWith("@@")) return cyan(line);
      if (line.startsWith("+")) return green(line);
      if (line.startsWith("-")) return red(line);
      return line;
    })
    .join("\n");
}

function planToJson(plan: FixPlan, applied: boolean): Record<string, unknown> {
  return {
    applied,
    filesScanned: plan.filesScanned,
    changes: plan.changes.map((c) => ({
      file: c.file,
      rewrites: c.rewrites,
      strippedParams: c.strippedParams,
    })),
    flags: plan.flags,
    skipped: plan.skipped,
    citations: { parameters: PARAM_RULE_CITATION, prompts: PROMPT_RULE_CITATION },
  };
}

function run(cmd: string, args: string[], cwd: string): { ok: boolean; out: string } {
  const result = spawnSync(cmd, args, { cwd, encoding: "utf8" });
  const out = `${result.stdout ?? ""}${result.stderr ?? ""}`.trim();
  return { ok: result.status === 0, out };
}

function openPullRequest(plan: FixPlan, root: string, branch: string, io: IO): number {
  const inRepo = run("git", ["rev-parse", "--is-inside-work-tree"], root);
  if (!inRepo.ok) {
    io.stderr("error: --pr needs a git repository.\n");
    return 2;
  }
  const gh = run("gh", ["--version"], root);
  if (!gh.ok) {
    io.stderr(
      "error: --pr needs the GitHub CLI (gh). Install it from https://cli.github.com and run gh auth login. The files were written.\n",
    );
    return 2;
  }
  const auth = run("gh", ["auth", "status"], root);
  if (!auth.ok) {
    io.stderr(
      `error: gh is not authenticated. Run gh auth login. The files were written.\n${auth.out}\n`,
    );
    return 2;
  }
  const steps: Array<[string, string[]]> = [
    ["git", ["checkout", "-b", branch]],
    ["git", ["add", "--", ...plan.changes.map((c) => c.file)]],
    [
      "git",
      [
        "commit",
        "-m",
        "Migrate retiring model IDs",
        "-m",
        "Generated by modelshift fix. Review the diff before merging.",
      ],
    ],
    ["git", ["push", "-u", "origin", branch]],
  ];
  for (const [cmd, args] of steps) {
    const result = run(cmd, args, root);
    if (!result.ok) {
      io.stderr(`error: ${cmd} ${args.join(" ")} failed:\n${result.out}\n`);
      return 2;
    }
  }
  const rewrites = plan.changes.reduce((n, c) => n + c.rewrites.length, 0);
  const stripped = plan.changes.reduce((n, c) => n + c.strippedParams.length, 0);
  const body = [
    `modelshift rewrote ${plural(rewrites, "model identifier")} in ${plural(plan.changes.length, "file")} and removed ${plural(stripped, "sampling parameter")}.`,
    "",
    ...plan.changes.flatMap((c) =>
      c.rewrites.map((r) => `- ${c.file}:${r.line} ${r.from} -> ${r.to} (${r.status})`),
    ),
    ...(plan.flags.length
      ? [
          "",
          "Prompt text to review:",
          ...plan.flags.map((f) => `- ${f.file}:${f.line} ${f.pattern}`),
        ]
      : []),
    "",
    "Run the affected prompts through `modelshift replay` before merging.",
  ].join("\n");
  const pr = run(
    "gh",
    ["pr", "create", "--title", "Migrate retiring model IDs", "--body", body, "--head", branch],
    root,
  );
  if (!pr.ok) {
    io.stderr(`error: gh pr create failed:\n${pr.out}\n`);
    return 2;
  }
  io.stdout(`${pr.out}\n`);
  return 0;
}

export async function runFix(argv: string[], io: IO): Promise<number> {
  const { values, positionals } = parse(argv, OPTIONS);
  if (flag(values, "help")) {
    io.stdout(FIX_HELP);
    return 0;
  }
  const root = resolveRoot(positionals, io);
  const days = int(values, "days", 90);
  const today = resolveToday(values);
  const index = loadIndex(values, io);
  const write = flag(values, "write") || flag(values, "pr");
  const plan = await planFix({
    root,
    days,
    today,
    index,
    includeEligible: flag(values, "include-eligible"),
    respectGitignore: !flag(values, "no-gitignore"),
  });
  if (write && plan.changes.length > 0) await applyFix(plan);
  if (flag(values, "json")) {
    io.stdout(`${JSON.stringify(planToJson(plan, write), null, 2)}\n`);
  } else {
    const rel = path.relative(io.cwd, root) || ".";
    const rewrites = plan.changes.reduce((n, c) => n + c.rewrites.length, 0);
    const stripped = plan.changes.reduce((n, c) => n + c.strippedParams.length, 0);
    io.stdout(
      `${bold("modelshift fix")} ${rel} ${dim(`(today ${today}, window ${days} days${write ? ", writing" : ", dry run"})`)}\n\n`,
    );
    if (plan.changes.length === 0) {
      io.stdout("No model identifiers to rewrite.\n");
    } else {
      const diff = renderUnifiedDiff(plan);
      io.stdout(`${io.isTTY ? colorDiff(diff) : diff}\n`);
    }
    if (stripped > 0) {
      io.stdout(
        `${yellow(`Removed ${plural(stripped, "sampling parameter")}.`)} ${PARAM_RULE_CITATION}\n\n`,
      );
    }
    if (plan.skipped.length > 0) {
      io.stdout(`${yellow("Skipped (no replacement named by the provider):")}\n`);
      for (const s of plan.skipped) io.stdout(`  ${s.file}:${s.line} ${s.id}\n`);
      io.stdout("\n");
    }
    if (plan.flags.length > 0) {
      io.stdout(`${yellow(`Prompt text to review (${plan.flags.length}):`)}\n`);
      for (const f of plan.flags)
        io.stdout(`  ${f.file}:${f.line} [${f.pattern}] ${dim(f.text)}\n`);
      io.stdout(`${PROMPT_RULE_CITATION}\n\n`);
    }
    if (plan.changes.length > 0) {
      io.stdout(
        write
          ? `${green(`Wrote ${plural(plan.changes.length, "file")}`)} (${plural(rewrites, "identifier")} rewritten, ${plural(stripped, "parameter")} removed).\n`
          : `${plural(plan.changes.length, "file")} would change (${plural(rewrites, "identifier")} rewritten, ${plural(stripped, "parameter")} removed). Run with --write to apply.\n`,
      );
    }
  }
  if (flag(values, "pr")) {
    if (plan.changes.length === 0) {
      io.stderr("Nothing to commit, no pull request opened.\n");
      return 0;
    }
    const branch = str(values, "branch") ?? `modelshift/migrate-${today}`;
    if (!/^[\w./-]+$/.test(branch)) throw new UsageError(`Invalid branch name "${branch}"`);
    return openPullRequest(plan, root, branch, io);
  }
  return 0;
}
